#pragma once

#define VARIABLE_REDEFINITION "identifier used for variable is already taken"
#define FUNCTION_REDEFINITION "identifier used for function is already taken"
#define ENUM_REDEFINITION "identifier used for an enum name is already taken"
#define ENUM_ITEM_REDEFINITION "identifier used for an enum item is already taken"
#define REPEATED_ENUM_VALUE "reuse of the same value for multiple enum items is not allowed"
#define REPEATED_CONJURED_ENUM_VALUE "reoccurence of a value for multiple enum items is not allowed"
#define MISSING_MAIN "no entry point function 'main' is defined"
#define BAD_MAIN_RETURN_TYPE "function main must have return type int"
#define STATIC_GLOBAL_VARIABLE "static global variables are not allowed"
#define GLOBAL_VARIABLE_DEFINITION_EXPRESSION "global varible must be initialised by literal"
#define MISPLACED_INT_LITERAL "cannot assign int literal"
#define MISPLACED_FLOAT_LITERAL "cannot assign float literal"
#define MISPLACED_BOOL_LITERAL "cannot assign bool literal"
#define MISPLACED_STRING_LITERAL "cannot assign string literal"
#define MISPLACED_STRING_VARIABLE "cannot assign literal other than type string"
#define CONSTANT_DECLARATION "constant assignment missing value"
#define REDEFINITION_OF_PARAMETER "identifier used for function parameter is already taken"

#define VARIABLE_SAME_AS_PARAMETER "variable name in functions top scope must not be the same as a its parameter"
#define LOCAL_VARIABLE_REDEFINITION "identifier used for variable is already taken in its scope"
#define FOR_HEADER_DEFINITION_WITH_SPECIFIER "definition in for header must not have a storage specifier"
#define BREAK_OUT_OF_LOOP "a break statement must be used within a loop"
#define CONTINUE_OUT_OF_LOOP "a continue statement must be used within a loop"
#define REDO_OUT_OF_LOOP "a redo statement must be used within a loop"
#define RESTART_OUT_OF_LOOP "a restart statement must be used within a loop"
#define UNDEFINED_VARIABLE "variable is undefined"
#define IMPLICIT_STRING_CONVERSION "cannot perform implicit conversion on subexpression of type string"
#define MODULE_ON_FLOAT "operator \"\%\" operands must not have type float"
#define BIT_FLOAT_OPERAND "bitwise operator operands must not have type float"
#define BIT_STRING_OPERAND "bitwise operator operands must not have type string"
#define READ_NOT_STRING "read must be used with a variable of type string"
#define READ_INTO_CONSTANT "cannot read into a constant variable"
#define WRITE_EXPRESSION "write argument may only be a single literal or variable of type string"
#define WRITE_NOT_STRING "write must be used with a variable of type string or a string literal"
#define ASSIGN_STRING_TO_OTHER "cannot assign value of type string"
#define ASSING_OTHER_TO_STRING "assigned value must be of type string"
#define LSIDE_NOT_ASSIGNABLE "left side of assignment must be a variable"
#define CONSTANT_ASSIGNMENT "cannot assign to a constant variable"
#define UNDEFINED_FUNCTION "function is undefined"
#define BAD_ARGUMENT_COUNT "function call has incorrect amount of arguments"
#define VOID_FUNCTION_IN_EXPRESSION "function used in an expression has return type void"
#define BAD_STRING_ARGUMENT "value of type string cannot be passed as argument here"
#define STRING_ARGUMENT_EXPECTED "argument of type string was expected here"
#define STRING_CONDITION "cannot evaluate value of type string as a condition"
#define FOR_HEADER_INIT_EXPRESSION "for loop inicialization may only be a variable definition or an only assignment"
#define FOR_HEADER_UPDATE_EXPRESSION "for loop update must be an only assignment"
#define BAD_RETURN_TYPE "return value type does not match the expected function return type"
#define BAD_EXIT_TYPE "exit value type cannot be converted to an int"

#define INTERNAL_ID_USE "identifiers may not start with \"__\" prefix"

#define UNDEFINED_ENUM_DECLARATION "variable declared as enum cannot use an undefined enum"
#define UNDEFINED_ENUM_PARAMETER "parameter cannot use an undefined enum as type"
#define UNDEFINED_ENUM_RETURN_TYPE "function return type cannot use an undefined enum"
#define GLOBAL_ENUM_VARIABLE "global variables of type enum are not allowed"

#define STATIC_INIT_NOT_LITERAL "static variables can only be initialised by literals"

#define INVALID_ARRAY_SIZE "array size may only be a positive integer"
#define STRING_ARRAY "array of type string is not allowed"
